services:
  backend:
    image: "ghcr.io/olegedly/multi-agent-rag-be:latest"
    expose:
      - "8000"
  frontend:
    image: "ghcr.io/olegedly/multi-agent-rag-fe:latest"
    expose:
      - "80"
    volumes:
      - "caddy_data:/data"
volumes:
  caddy_data: null
